# -*- coding: utf-8 -*-
"""
GameUI 协议（M3-T05 / M3-T01）

定义 UI 后端必须实现的方法集合。
RichTerminalUI, TerminalUI, TextualUI 均实现此协议。
"""

from __future__ import annotations
from typing import Optional, List, Tuple, Any, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from game.player import Player
    from game.card import Card, CardSuit
    from game.engine import GameEngine
    from game.hero import Hero


class GameUI(Protocol):
    """UI 后端协议"""

    # ==================== 菜单 ====================

    def show_title(self) -> None: ...
    def show_main_menu(self) -> int: ...
    def show_player_count_menu(self) -> int: ...
    def show_difficulty_menu(self) -> str: ...
    def show_hero_selection(
        self, heroes: List[Hero], selected_count: int = 1, is_lord: bool = False
    ) -> List[Hero]: ...
    def show_rules(self) -> None: ...

    # ==================== 游戏状态 ====================

    def set_engine(self, engine: GameEngine) -> None: ...
    def show_game_state(self, engine: GameEngine, current_player: Player) -> None: ...
    def show_log(self, message: str) -> None: ...
    def show_game_over(self, winner_message: str, is_victory: bool) -> None: ...
    def clear_screen(self) -> None: ...

    # ==================== 玩家操作 ====================

    def get_player_action(self) -> str: ...
    def choose_target(
        self, player: Player, targets: List[Player], prompt: str = "选择目标"
    ) -> Optional[Player]: ...
    def choose_card_to_play(self, player: Player) -> Optional[Card]: ...
    def choose_cards_to_discard(self, player: Player, count: int) -> List[Card]: ...
    def show_skill_menu(
        self, player: Player, usable_skills: List[str]
    ) -> Optional[str]: ...

    # ==================== 响应请求 ====================

    def ask_for_shan(self, player: Player) -> Optional[Card]: ...
    def ask_for_sha(self, player: Player) -> Optional[Card]: ...
    def ask_for_tao(self, savior: Player, dying: Player) -> Optional[Card]: ...
    def ask_for_wuxie(
        self,
        responder: Player,
        trick_card: Card,
        source: Player,
        target: Optional[Player],
        currently_cancelled: bool,
    ) -> Optional[Card]: ...
    def choose_card_from_player(
        self, chooser: Player, target: Player
    ) -> Optional[Card]: ...
    def choose_suit(self, player: Player) -> CardSuit: ...
    def guanxing_selection(
        self, player: Player, cards: List[Card]
    ) -> Tuple[List[Card], List[Card]]: ...

    # ==================== 其他 ====================

    def show_help(self) -> None: ...
    def wait_for_continue(self, message: str = "Press Enter to continue...") -> None: ...
    def ask_for_jijiang(self, player: Player) -> Optional[Card]: ...
    def ask_for_hujia(self, player: Player) -> Optional[Card]: ...
